services:
  backend:
    container_name: backend
    build: ./backend
    ports:
      - "3000:3000"
    environment:
      BACK_END_PORT: 3000
    depends_on:
      - db
  frontend:
    container_name: frontend
    build: ./frontend
    ports:
      - "8000:8000"
    environment:
      FRONT_END_PORT: 8000
    depends_on:
      - backend
    
  db:
    image: mysql:latest
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: '1234'
      MYSQL_DATABASE: calendardb
    ports:
      - "3307:3306"
    volumes:
      - ./data:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: '1234'
    ports:
      - '8080:80'
    depends_on:
      - db